In [1]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split


In [2]:
text=pd.read_csv('textclass.csv')
text

Type          word1        word2       word3        word4  \
0   machine learning          field    Computer      Science  statistical   
1   machine learning  computational  unsupervise  supervised         data   
2   machine learning  computational  unsupervise  supervised         data   
3   machine learning          field    Computer      Science  statistical   
4   machine learning          field    Computer      Science  statistical   
5   machine learning          field    Computer      Science  statistical   
6   machine learning          field    Computer      Science  statistical   
7   machine learning     analystics    automates       human         make   
8   machine learning         branch         idea    identify      pattern   
9   machine learning         branch         idea    identify      pattern   
10          Big Data          large    extremely        data         sets   
11          Big Data          large    extremely        data         sets   
12          Big Data        variety     velocity      volume      capture   
13          Big Data       business  informatics         big         data   
14          Big Data       business  informatics         big         data   
15          Big Data       business  informatics         big         data   
16          Big Data        variety     velocity      volume      capture   
17          Big Data        variety     velocity      volume      capture   
18          Big Data        variety     velocity      volume      capture   
19          Big Data        variety     velocity      volume      capture   

         word5       word6          word7      word8  
0   techniques     pattern    recognition  filtering  
1       mining  scientists     prediction      learn  
2       mining  scientists     prediction      learn  
3   techniques     pattern    recognition  filtering  
4   techniques     pattern    recognition  filtering  
5   techniques     pattern    recognition  filtering  
6   techniques     pattern    recognition  filtering  
7     decision     minimal   intervention  analystic  
8     decision        make     analytical      model  
9     decision        make     analytical      model  
10  voluminous     complex           data    storage  
11  voluminous     complex           data    storage  
12     sharing    transfer  visualization   analysis  
13        grow     rapidly        diverse        big  
14        grow     rapidly        diverse        big  
15        grow     rapidly        diverse        big  
16     sharing    transfer  visualization   analysis  
17     sharing    transfer  visualization   analysis  
18     sharing    transfer  visualization   analysis  
19     sharing    transfer  visualization   analysis

In [3]:
#hearder removing
text=pd.read_csv('textclass.csv',header=None)

text=pd.read_csv('textclass.csv',header=None,usecols=range(0,9),skiprows=1)
text

0              1            2           3            4  \
0   machine learning          field    Computer      Science  statistical   
1   machine learning  computational  unsupervise  supervised         data   
2   machine learning  computational  unsupervise  supervised         data   
3   machine learning          field    Computer      Science  statistical   
4   machine learning          field    Computer      Science  statistical   
5   machine learning          field    Computer      Science  statistical   
6   machine learning          field    Computer      Science  statistical   
7   machine learning     analystics    automates       human         make   
8   machine learning         branch         idea    identify      pattern   
9   machine learning         branch         idea    identify      pattern   
10          Big Data          large    extremely        data         sets   
11          Big Data          large    extremely        data         sets   
12          Big Data        variety     velocity      volume      capture   
13          Big Data       business  informatics         big         data   
14          Big Data       business  informatics         big         data   
15          Big Data       business  informatics         big         data   
16          Big Data        variety     velocity      volume      capture   
17          Big Data        variety     velocity      volume      capture   
18          Big Data        variety     velocity      volume      capture   
19          Big Data        variety     velocity      volume      capture   

             5           6              7          8  
0   techniques     pattern    recognition  filtering  
1       mining  scientists     prediction      learn  
2       mining  scientists     prediction      learn  
3   techniques     pattern    recognition  filtering  
4   techniques     pattern    recognition  filtering  
5   techniques     pattern    recognition  filtering  
6   techniques     pattern    recognition  filtering  
7     decision     minimal   intervention  analystic  
8     decision        make     analytical      model  
9     decision        make     analytical      model  
10  voluminous     complex           data    storage  
11  voluminous     complex           data    storage  
12     sharing    transfer  visualization   analysis  
13        grow     rapidly        diverse        big  
14        grow     rapidly        diverse        big  
15        grow     rapidly        diverse        big  
16     sharing    transfer  visualization   analysis  
17     sharing    transfer  visualization   analysis  
18     sharing    transfer  visualization   analysis  
19     sharing    transfer  visualization   analysis

In [4]:
#convert array
x=pd.read_csv('textclass.csv',header=None,usecols=range(1,9),skiprows=1)
x=np.array(x)
x

array([['field', 'Computer ', 'Science', 'statistical', 'techniques',
        'pattern', 'recognition', 'filtering'],
       ['computational', 'unsupervise', 'supervised', 'data', 'mining',
        'scientists', 'prediction', 'learn'],
       ['computational', 'unsupervise', 'supervised', 'data', 'mining',
        'scientists', 'prediction', 'learn'],
       ['field', 'Computer ', 'Science', 'statistical', 'techniques',
        'pattern', 'recognition', 'filtering'],
       ['field', 'Computer ', 'Science', 'statistical', 'techniques',
        'pattern', 'recognition', 'filtering'],
       ['field', 'Computer ', 'Science', 'statistical', 'techniques',
        'pattern', 'recognition', 'filtering'],
       ['field', 'Computer ', 'Science', 'statistical', 'techniques',
        'pattern', 'recognition', 'filtering'],
       ['analystics', 'automates', 'human', 'make', 'decision',
        'minimal', 'intervention', 'analystic'],
       ['branch', 'idea', 'identify', 'pattern', 'decision', 

In [5]:
#convert array (textclass)
y=pd.read_csv('textclass.csv',header=None,usecols=range(0,1),skiprows=1)
y=np.array(y)
y

array([['machine learning'],
       ['machine learning'],
       ['machine learning'],
       ['machine learning'],
       ['machine learning'],
       ['machine learning'],
       ['machine learning'],
       ['machine learning'],
       ['machine learning'],
       ['machine learning'],
       ['Big Data'],
       ['Big Data'],
       ['Big Data'],
       ['Big Data'],
       ['Big Data'],
       ['Big Data'],
       ['Big Data'],
       ['Big Data'],
       ['Big Data'],
       ['Big Data']], dtype=object)

In [6]:
#encoding
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
le.fit(y)
y=le.transform(y)
y

C:\Users\DELL\Anaconda3\envs\tt\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\DELL\Anaconda3\envs\tt\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
#encoding all features with loop
from sklearn import preprocessing
for j in range(0,8):
    le.fit(x[:,j])
    x[:,j]=le.transform(x[:,j])
#fe=preprocessing.LabelEncoder()
#fe.fit(x)
#x=fe.transform(x)
x

array([[4, 0, 0, 5, 4, 3, 5, 3],
       [3, 5, 5, 1, 2, 5, 4, 4],
       [3, 5, 5, 1, 2, 5, 4, 4],
       [4, 0, 0, 5, 4, 3, 5, 3],
       [4, 0, 0, 5, 4, 3, 5, 3],
       [4, 0, 0, 5, 4, 3, 5, 3],
       [4, 0, 0, 5, 4, 3, 5, 3],
       [0, 1, 3, 2, 0, 2, 3, 1],
       [1, 3, 4, 3, 0, 1, 0, 5],
       [1, 3, 4, 3, 0, 1, 0, 5],
       [5, 2, 2, 4, 5, 0, 1, 6],
       [5, 2, 2, 4, 5, 0, 1, 6],
       [6, 6, 6, 0, 3, 6, 6, 0],
       [2, 4, 1, 1, 1, 4, 2, 2],
       [2, 4, 1, 1, 1, 4, 2, 2],
       [2, 4, 1, 1, 1, 4, 2, 2],
       [6, 6, 6, 0, 3, 6, 6, 0],
       [6, 6, 6, 0, 3, 6, 6, 0],
       [6, 6, 6, 0, 3, 6, 6, 0],
       [6, 6, 6, 0, 3, 6, 6, 0]], dtype=object)

In [8]:
#train
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=12)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(16, 8) (4, 8) (16,) (4,)


In [9]:
#SVM
from sklearn.svm import SVC
clf=SVC(kernel="poly")              #'linear' , 'rbf' , 'poly' , 'sigmoid'
clf.fit(x_train,y_train)


C:\Users\DELL\Anaconda3\envs\tt\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [10]:
#input text encode
test=["field","Computer","Science","statistical","techniques","pattern","recognition","filtering"]
le=preprocessing.LabelEncoder()
le.fit(test)
test=le.transform(test)
test

array([2, 0, 1, 6, 7, 4, 5, 3], dtype=int64)

In [11]:
t=clf.predict(test)
print(t)
if(t==1):
    print("Input Text is machine Learning")
if(t==0):
    print("Input Text is Big data")
tt 

ValueError: Expected 2D array, got 1D array instead:
array=[2. 0. 1. 6. 7. 4. 5. 3.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [10]:
#Testing with input data
test=[4, 0, 0, 5, 4, 3, 5, 3]
test=np.array(test)
tt=test.reshape(1,-1)

t=clf.predict(tt)
print(t)

[1]


In [11]:
#input text encode
test=["field","Computer","Science","statistical","techniques","pattern","recognition","filtering"]
le=preprocessing.LabelEncoder()
le.fit(test)
test=le.transform(test)
test

array([2, 0, 1, 6, 7, 4, 5, 3], dtype=int64)

In [12]:
#Testing with input data

test=np.array(test)
tt=test.reshape(1,-1)

t=clf.predict(tt)
print(t)
if(t==1):
    print("Input Text is machine Learning")
if(t==0):
    print("Input Text is Big data")
tt   

[1]
Input Text is machine Learning


array([[2, 0, 1, 6, 7, 4, 5, 3]], dtype=int64)

In [13]:
inputtext=input("Enter Text")
inputarr=inputtext.split(' ')
#encode
le=preprocessing.LabelEncoder()
le.fit(inputarr)
test=le.transform(inputarr)
test
#predict
test=np.array(test)
tt=test.reshape(1,-1)

t=clf.predict(tt)
print(t)
if(t==1):
    print("Input Text is machine Learning")
if(t==0):
    print("Input Text is Big data")
#else: print("wrong")
    


Enter Text[2, 0, 1, 6, 7, 4, 5, 3]
[1]
Input Text is machine Learning
